### ISSUE TITLE
2020 text edits

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/wq-static#13]
Figures 1 & 5 add note about missing data

2020 Decision Matrix Results  
The nuisance alga, _Pyrodinium bahamense_, was again reported in Old Tampa Bay (OTB) during June - September 2020, contributing to a large magnitude chlorophyll-a exceedance that has persisted for a long duration (6 yrs). 

Page 1 Note: Add hyphen to "#04-00"

Maintaining Reasonable Assurance & TMDL Compliance
During 2020, the COVID-19 pandemic precluded water quality data collection in April and May. As a result, compliance determinations have not been made for any bay segments. Results shown in Figure 5 depict chlorophyll-a concentrations in relation to regulatory criteria, as calculated without observations from the months noted above. The fourth RA annual assessment report for the 2017-2021 period will be submitted in April 2021.

2020 Chl-a Monthly Variation
summer months.  and DELETE "Lower Tampa Bay also showed elevated concentrations in August 2019, potentially due to non-harmful algae blooms."

Tampa Bay Seagrass Recovery
SWFWMD coverage estimates from the winter 2019-20 period will be available in spring 2021. More information on assessments of the bay’s seagrass recovery using transect monitoring data can be found at https://shiny.tbep.org/seagrasstransect-dash/. 

Progress Towards Meeting Regulatory Goals
Update note at bottom--
Note: : 2020 Tampa Bay Reasonable Assurance Assessment available from Sherwood, E., Burke, M. 2021. TBEP Technical Report #XX-21. Please cite this document as Beck, M.W., Burke, M., Raulerson, G. 2020. 2020 Tampa Bay Water Quality Assessment. Tampa Bay Estuary Program Technical Report #XX-21, St. Petersburg, FL.

**Comment by emseabee** [comment]
@esherwoo77 take a look at the proposed language above (esp the maintaining reasonable assurance section) and let @fawda123 if you are comfortable with it

**Comment by esherwoo77** [comment]
@fawda123 and @emseabee : I edited and added my comments to Maya's string above. Otherwise looks good. EPCHC just sent out an email indicating Dec. 2020 data is final, so we should be able to produce a 'final' report now.

**Comment by fawda123** [comment]
@esherwoo77 @emseabee Here's the updated pdf. Let me know if this looks good  so I can close this issue and get this on our pub page. 

https://tbep-tech.github.io/wq-static/wq.pdf

**Comment by esherwoo77** [comment]
The last sentence in Figure 6 can be deleted too: “Historic chlorophyll-a annual averages for the four bay segments.” After that, I think you can finalize.

**Comment by emseabee** [comment]
good to go!
