### ISSUE TITLE
Seagrass target change

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/wq-static#14]
Bottom of page 2, the seagrass target, per the 2020 HMPU, is now 40,000 acres (not 38k). Per Maya change the text now and we'll wait for the 2020 seagrass numbers to update the graph?

And I was poking a few things, couldn't figure out where to try and make the change myself. I think I looked at all of the text-ish files but no joy.

**Comment by emseabee** [comment]
@esherwoo77 has advised to finalize prior to obtaining seagrass numbers, meaning we'll catch it in 2021

**Comment by fawda123** [comment]
Gary did the thing cdb42ed7725ed4f8215a0835bd85608713806e7c
