### ISSUE TITLE
piney point reference

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/wq-static#16]
consider moving the piney point and red tide sentences to the chlorophyll section, provide a little separation from the regulatory compliance?

**Comment by fawda123** [comment]
Done, I just moved the text. There's obviously a lot more to say about it (e.g., why didn't we see spikes in LTB/MTB?), but brevity is probably good here.

**Comment by esherwoo77** [comment]
I've read through the text of the document and think it accurately tells the story. I approve accordingly. Thanks for moving so quickly on this.
