### ISSUE TITLE
Compliance report link

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/wq-static#2]
Link/biblio for the 2nd report: 

https://www.tbeptech.org/TBEP_TECH_PUBS/2019/TBEP_11-19_TBNMC_2018_RA_Annual_Assessment.pdf  

2018 Tampa Bay Estuary Nutrient Management Compliance Assessment.  2019. Technical Report #11-19 of the Tampa Bay Estuary Program (E.T. Sherwood and M. Burke). 15 pp.

**Comment by fawda123** [comment]
Done here cfdaf4d354b6cab16ee1e33a010ebef8b15ef606 but this will not be the final format, just setting up a workflow to get refs in from https://github.com/tbep-tech/tbep-refs
