### ISSUE TITLE
Graph background

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/wq-static#8]
Looking good! I think the graphs need a different background (maybe white-ish), colors are fading into the green for me

**Comment by Gmangrove** [comment]
1) * [x] Top of 1 - Hotlinks for all the logos?
1) * [x] Bottom of page 2, needs to be tech report #11-19
1) * [x] Pretty sure that OTB is a large magnitude exceedance? Well over 2SE
1) * [x] Seagrass paragraph, 2nd sentence '2018'
1) * [x] Seagrass paragraph, 2nd sentence, seagrass acreage is 40,652
1) * [x] Seagrass paragraph, last sentence, suggest tech pub #09-17, can you also please link: https://www.tbeptech.org/TBEP_TECH_PUBS/2017/TBEP_09_17_Sherwood_et_al_TB_Seagrass_SE_Geographer_project_muse_667989.pdf

**Comment by fawda123** [comment]
The graph backgrounds are fixed, I was incorrectly using a transparent gray color that let the background bleed through.  https://github.com/tbep-tech/tbeptools/commit/ff41dc4cce071d0f90e9d7f8ff5c51f0eb52e3cf

**Comment by fawda123** [comment]
1 addressed here 105b5ab9551162e74ba43851e24003752a90d986

**Comment by fawda123** [comment]
2 addressed here b35686c2801cc17e916b046d4f0780c1a640ceb8

**Comment by fawda123** [comment]
4, 5, 6 addressed here ef3793223cf1bb9e5385e2abfd127b55705cde31

**Comment by fawda123** [comment]
3 addressed here 65bd82398c7163141f91ce2ac6749c84859392b7

**Comment by fawda123** [comment]
@Gmangrove have a look at the edits and please close the issue if they look good!

**Comment by Gmangrove** [comment]
All looks good to me, please double-check with Ed or Maya re the large-magnitude exceedance statement, I'm 99% sure it's correct. Thanks!
